---
title: "DataFest 2017"
author: "Karen Diaz, Diana Fierros-Piña, Marisa Youngblood, Tara Marin, and Marta García"
date: "3/31/2017"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
library(maps)

datafest <- clicks
```

```{r}

datafest1 <- datafest %>%
  mutate(srch_checkin = ymd(srch_ci)) %>%
  inner_join(destinations, by = "srch_destination_id") %>%
  select(user_location_country, 
         user_location_region,
         srch_destination_latitude,
         srch_destination_longitude,
         orig_destination_distance,
         srch_destination_id,
         srch_destination_name,
         srch_checkin, 
         is_booking) %>%
  filter(is_booking == '1', user_location_country == 'UNITED STATES OF AMERICA')

top_five_dest <- datafest1 %>%
  group_by(user_location_region) %>%
  count(srch_destination_name, sort = TRUE) %>%
  group_by(user_location_region) %>%
  slice(1:5) %>%
  arrange(desc(n)) 

  

new_table <- destinations %>%
  select(srch_destination_name,
         srch_destination_latitude,
         srch_destination_longitude) 


beta_together <- top_five_dest %>%
  left_join(new_table, top_five_dest, by = "srch_destination_name") %>%
  filter(user_location_region == "FL")

```

###Florida
```{r}
legend_title <- legend_title <- "Number \nof People"

states <- map_data("state")

usa <-map_data("usa")

florida_together <- top_five_dest %>%
  left_join(new_table, top_five_dest, by = "srch_destination_name") %>%
  filter(user_location_region == "FL")

fl_df <- subset(states, region == "florida")

fl_base <- ggplot(data = states) +
  geom_polygon(aes(x=long, y = lat, group = group), color = 'white', fill = "lightgray") + 
  coord_fixed(1.3) + 
  guides(fill=FALSE) +
  geom_polygon(data = fl_df, mapping = aes(x = long, y = lat, group = group), fill = "#66ccff") + 
  geom_count(data = florida_together, aes(srch_destination_longitude, srch_destination_latitude, size = n), color = "#ffb366") + scale_size(legend_title)

fl_base
```

###Texas
```{r, fig.width = 15, fig.height = 10}

legend_title <- legend_title <- "Number \nof People"

texas_together <- top_five_dest %>%
  left_join(new_table, top_five_dest, by = "srch_destination_name") %>%
  filter(user_location_region == "TX")

tx_df <- subset(states, region == "texas")

tx_base <- ggplot(data = states) +
  geom_polygon(aes(x = long, y = lat, group = group), color = 'white', fill = "lightgray") + 
  coord_fixed(1.3) + 
  guides(fill=FALSE) +
  geom_polygon(data = tx_df, mapping = aes(x = long, y = lat, group = group), fill = "#66ccff") + 
  geom_count(data = texas_together, aes(srch_destination_longitude, srch_destination_latitude, size = n), color = "#ffb366") + scale_size(legend_title)

tx_base
```

###New York
```{r}
ny_together <- top_five_dest %>%
  left_join(new_table, top_five_dest, by = "srch_destination_name") %>%
  filter(user_location_region == "NY")


states <- map_data("state")

usa <-map_data("usa")


ny_df <- subset(states, region == "new york")

us_base <- ggplot(data = states) +
  geom_polygon(aes(x=long, y = lat, group = group), color = 'white', fill = "lightgray") + 
  coord_fixed(1.3) + 
  guides(fill=FALSE)

legend_title <- "Number \nof People"

us_base + geom_polygon(data = ny_df, mapping = aes(x = long, y = lat, group = group), fill = "#66ccff") + geom_count(data = ny_together, aes(srch_destination_longitude, srch_destination_latitude, size = n), color = "#ffb366") + scale_size(legend_title)



```

###Illinois
```{r}
legend_title <- "Number \nof People"

il_together <- top_five_dest %>%
  left_join(new_table, top_five_dest, by = "srch_destination_name") %>%
  filter(user_location_region == "IL")

il_df <- subset(states, region == "illinois")

il_base <- ggplot(data = states) +
  geom_polygon(aes(x=long, y = lat, group = group), color = 'white', fill = "lightgray") + 
  coord_fixed(1.3) + 
  guides(fill=FALSE) +
  geom_polygon(data = il_df, mapping = aes(x = long, y = lat, group = group), fill = "#66ccff") + 
  geom_count(data =il_together, aes(srch_destination_longitude, srch_destination_latitude, size = n), colour = "#ffb366") + scale_size(legend_title)

il_base
```
###California
```{r}
legend_title <- "Number \nof People"

ca_together <- top_five_dest %>%
  left_join(new_table, top_five_dest, by = "srch_destination_name") %>%
  filter(user_location_region == "CA")

ca_df <- subset(states, region == "california")

ca_base <- ggplot(data = states) +
  geom_polygon(aes(x=long, y = lat, group = group), color = 'white', fill = "lightgray") + 
  coord_fixed(1.3) + 
  guides(fill=FALSE) +
  geom_polygon(data = ca_df, mapping = aes(x = long, y = lat, group = group), fill = "#66ccff") + 
  geom_count(data = ca_together, aes(srch_destination_longitude, srch_destination_latitude, size = n), color = "#ffb366") + scale_size(legend_title)

ca_base
```







